apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alertmanager
    release: alertmanager
  name: alertmanager
spec:
  ports:
  - name: alertmanager
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: alertmanager
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
  name: alertmanager-0
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
      name: alertmanager
  selector:
    statefulset.kubernetes.io/pod-name: alertmanager-0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
  name: alertmanager-1
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
      name: alertmanager
  selector:
    statefulset.kubernetes.io/pod-name: alertmanager-1
