apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: alertmanager
  name: alertmanager
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      run: alertmanager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: alertmanager
    spec:
      containers:
      - image: prom/alertmanager:v0.18.0
        name: alertmanager
        ports:
        - containerPort: 9093
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
        volumeMounts:
        - mountPath: /etc/alertmanager/alertmanager.yml
          name: config
          subPath: alertmanager.yml
      volumes:
      - configMap:
          items:
          - key: alertmanager.yml
            path: alertmanager.yml
          name: alertmanager-config
        name: config
status: {}
