apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: alertmanager
  name: alertmanager
  namespace: monitor
spec:
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
    nodePort: 31003
  selector:
    run: alertmanager
  type: NodePort
status:
  loadBalancer: {}
