groups:
- name: kafka.rules
  rules:

  - alert: KafkaBrokerNum 
    expr: kafka_brokers < 3
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Kafka instance {{ $labels.instance }} broker number is 0."
      description: "Kafka instance {{ $labels.instance }} broker number is 0.."

  #- alert: KafkaTopicsReplicas
  #  expr: sum(kafka_topic_partition_in_sync_replica) by (topic) < 3
  #  for: 5m
  #  labels:
  #    severity: critical
  #  annotations:
  #    summary: "Kafka topics replicas (instance {{ $labels.instance }})"
  #    description: "Kafka topic in-sync partition\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
