groups:
- name: mysql.rules
  rules:

  # Alert for instance that is unreachable for >5 minutes.
  - alert: mysql_instance_down
    expr: mysql_up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} in {{ $labels.environment }} has been down for more than 2 minutes."

#  - alert: MySQLInnoDBLogWaits
#    expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
#    labels:
#      severity: warning
#    annotations:
#      description: "Instance {{ $labels.instance }} in {{ $labels.environment }} innodb logs are waiting for disk at a rate of {{$value}}/second"
#      summary: "MySQL innodb log writes stalling"
#
#  - alert: MySQLAbortClient
#    expr: mysql_global_status_aborted_clients > 500
#    labels:
#      severity: warning
#    annotations:
#      description: "Instance {{ $labels.instance }} in {{ $labels.environment }} abort client is too much,current value is {{$value}}."
#      summary: "MySQL abort client is too much."
#
#  - alert: MySQLAbortConnect
#    expr: mysql_global_status_aborted_connects > 1000
#    labels:
#      severity: warning
#    annotations:
#      description: "Instance {{ $labels.instance }} in {{ $labels.environment }} abort connect is too much,current value is {{$value}}."
#      summary: "MySQL abort connect is too much."
