groups:
- name: pod.rules
  rules:

#  - alert: pod_memory_fail
#    expr: rate(container_memory_failcnt{image!=""}[5m]) > 0
#    for: 5m
#    labels:
#      severity: critical
#    annotations:
#      description: "容器 {{ $labels.name }} 申请内存失败 , (current count is {{ $value }})"
#      summary: "内存申请失败告警"

  - alert: PodFrequentlyRestarting
    expr: kube_pod_container_status_restarts_total{namespace=~"paas|monitor"} > 3
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{$labels.environment}}.{{$labels.namespace}}.{{$labels.pod}} was restarted {{$value}} times within the last hour"
      description: "Pod {{$labels.namespace}}/{{$labels.pod}} was restarted {{$value}} times within the last hour"

  - alert: PodStatusNotRunning
    expr: kube_pod_status_phase{namespace=~"cert-manager|consul|falco|ingress-nginx|keycloak|paas|nuclio|monitor|observability|presto|rancher|trivy|pgo",phase=~"Failed|Unknown|Evicted|Pending|CrashLoopBackOff|Error"} == 1
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod }} in {{ $labels.environment }}.{{ $labels.namespace }} is not running  Current status is {{ $value }}"
      description: Pod {{ $labels.pod }} in {{ $labels.environment }}.{{ $labels.namespace }} is not running.

  - alert: ContainerCpuUsage
    expr: sum by(pod_name,namespace,environment) (rate(container_cpu_usage_seconds_total{namespace=~"cert-manager|consul|falco|ingress-nginx|keycloak|paas|nuclio|monitor|observability|presto|rancher|trivy"}[5m])) / (sum by(pod_name,namespace,environment) (container_spec_cpu_quota{namespace=~"cert-manager|consul|falco|ingress-nginx|keycloak|paas|nuclio|monitor|observability|presto|rancher|trivy"} / 100000)) * 100 > 75
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod_name }} in {{ $labels.environment }}.{{ $labels.namespace }} CPU Usage is high. VALUE = {{ $value }}"
      description: "Container CPU usage is above 80%\n VALUE = {{ $value }}\n LABELS: {{ $labels }}"

  - alert: ContainerMemoryUsage
    expr: sum by(pod_name,namespace,environment) (container_memory_rss{namespace=~"cert-manager|consul|falco|ingress-nginx|keycloak|paas|nuclio|monitor|observability|presto|rancher|trivy"}) / sum by(pod_name,namespace,environment) (container_spec_memory_limit_bytes{namespace=~"cert-manager|consul|falco|ingress-nginx|keycloak|paas|nuclio|monitor|observability|presto|rancher|trivy"}) * 100 != +Inf  >  90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Pod {{ $labels.pod_name }} in {{ $labels.environment }}.{{ $labels.namespace }} Memory Usage is high. VALUE = {{ $value }}"
      description: "Container Memory usage is above 80%\n VALUE = {{ $value }}\n LABELS: {{ $labels }}"

  # A container has disappeared
  # - alert: ContainerDisappeared
  #   expr:  time() - avg ( container_last_seen{namespace=~"cert-manager|consul|falco|ingress-nginx|keycloak|paas|nuclio|monitor|observability|presto|rancher|trivy",pod !~ ".*cronjob.*" }  ) by ( app,job,namespace,pod_name ) > 120
  #   for: 2m
  #   labels:
  #     severity: warning
  #   annotations:
  #     summary: "Container {{ $labels.environment }}.{{ $labels.namespace }}.{{ $labels.pod_name }}  has disappeared for 2 minites"
  #     description: "A container has disappeared\n VALUE = {{ $value }}\n  LABELS: {{ $labels }} "