apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitor
  labels:
    k8s-app: kube-state-metrics
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  type: NodePort
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    nodePort: 31003
    protocol: TCP
  - name: telemetry
    port: 8081
    targetPort: telemetry
    nodePort: 31003
    protocol: TCP
  selector:
    k8s-app: kube-state-metrics
