name: minio
version: 4.3.0
apiVersion: v1
appVersion: 1.0.0
keywords:
- storage
- object-storage
- S3
description: Minio is a high performance distributed object storage server, designed
  for large-scale private cloud infrastructure.
home: http://www.paas.com
icon: http://mart.chebai.com:30024/images/icon/icosmonitor.jpg
maintainers:
- email: sre@gcstgroup.com
  name: sre
sources:
- http://www.paas.com