{{- if .Values.persistence.enabled }}
{{- range $zkIndex,$map :=  .Values.persistence.pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $map.name }}
{{- if $.Values.persistence.annotations }}
  annotations:
{{ toYaml $.Values.persistence.annotations | indent 4 }}
{{- end }}
{{- if $.Values.persistence.labels }}
  labels:
{{ toYaml $.Values.persistence.labels | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $map.size }}
  storageClassName: {{ toYaml $.Values.persistence.storageClass }}
---
{{- end }}
{{- end }}
 
