apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: blackbox
  name: blackboxexporter-monitor
  namespace: monitor
spec:
  ports:
  - port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    run: blackbox
status:
  loadBalancer: {}
