apiVersion: v1
kind: ConfigMap
metadata:
  name: bucketconfig
  namespace: monitor
data:
  config.yaml: |
    type: S3
    config:
      bucket: "prometheus"
      endpoint: "minio:9000"
      access_key: "AKIAIOSFODNN7EXAMPLE"
      secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      insecure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitor
data:
  prometheus.yaml.tmpl: |-
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      external_labels:
        datacenter: thanos-prometheus
        # Each Prometheus has to have unique labels.
        replica: $(HOSTNAME)

    rule_files:
    - /etc/prometheus/rules/*.rules

    #alerting:
    #  alertmanagers:
    #  - scheme: http
    #    static_configs:
    #    - targets:
    #      - "alertmanager-headless:9093"
            #- "alertmanager-1.alertmanager:9093"


    scrape_configs:
    - job_name: 'federate'
      scrape_interval: 30s
      scrape_timeout: 30s
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]':
          - '{job=~"kubernetes-.*|blackbox.*"}'
      static_configs:
        - targets:
          - 'monitor-prometheus-dev-monitor.example.city'
          labels:
            environment: dev

    - job_name: 'prometheus'
      static_configs:
      - targets: 
        - 'prometheus-0:9090'
        - 'prometheus-1:9090'

    - job_name: 'alertmanager'
      static_configs:
      - targets: 
        - 'alertmanager-0.alertmanager:9093'
        - 'alertmanager-1.alertmanager:9093'
        - 'alertmanager-2.alertmanager:9093'

    - job_name: 'thanos'
      static_configs:
      - targets:
        - 'thanos-querier:9090'  
        - 'sidecar-0:10902'
        - 'sidecar-1:10902'
        - 'thanos-store-0.thanos-store:10902'
        - 'thanos-store-1.thanos-store:10902'
        - 'thanos-rule-0.thanos-rule:10902'
        - 'thanos-rule-1.thanos-rule:10902'
        - 'thanos-compactor:10902'
        - 'thanos-bucket:10902'

    - job_name: 'minio'
      metrics_path: /minio/prometheus/metrics
      scheme: http
      static_configs:
      - targets: ['minio:9000']
