apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: object-store-bucket-debugging
    app.kubernetes.io/instance: thanos-bucket
    app.kubernetes.io/name: thanos-bucket
    app.kubernetes.io/version: master-2020-08-11-2ea2c2b7
  name: thanos-bucket
  # namespace: thanos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: object-store-bucket-debugging
      app.kubernetes.io/instance: thanos-bucket
      app.kubernetes.io/name: thanos-bucket
  template:
    metadata:
      labels:
        app.kubernetes.io/component: object-store-bucket-debugging
        app.kubernetes.io/instance: thanos-bucket
        app.kubernetes.io/name: thanos-bucket
        app.kubernetes.io/version: master-2020-08-11-2ea2c2b7
    spec:
      containers:
      - args:
        - tools
        - bucket
        - web
        - --log.level=info
        - --objstore.config-file=/etc/bucket/config.yaml
        # env:
        # - name: OBJSTORE_CONFIG
        #   valueFrom:
        #     secretKeyRef:
        #       key: thanos.yaml
        #       name: thanos-objectstorage
        image: reg.chebai.org/paas/thanos:v0.15.0
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        name: thanos-bucket
        ports:
        - containerPort: 10902
          name: http
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
          - name: bucketconfig
            mountPath: /etc/bucket
      volumes:
        - name: bucketconfig
          configMap:
            name: bucketconfig        
      terminationGracePeriodSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: object-store-bucket-debugging
    app.kubernetes.io/instance: thanos-bucket
    app.kubernetes.io/name: thanos-bucket
    app.kubernetes.io/version: master-2020-08-11-2ea2c2b7
  name: thanos-bucket
  # namespace: thanos
spec:
  ports:
  - name: http
    port: 10902
    targetPort: http
  selector:
    app.kubernetes.io/component: object-store-bucket-debugging
    app.kubernetes.io/instance: thanos-bucket
    app.kubernetes.io/name: thanos-bucket
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bucket
  namespace: monitor
spec:
  rules:
  - host: bucket.example.org
    http:
      paths:
      - path: 
        backend:
          serviceName: thanos-bucket
          servicePort: 10902    