---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: pg-prometheus
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: pg-prometheus
status:
  loadBalancer: {}
