apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: prometheus-postgresql-adapter
spec:
  ports:
  - port: 9201
    protocol: TCP
    targetPort: 9201
  selector:
    run: prometheus-postgresql-adapter
status:
  loadBalancer: {}
