
# kubectl create secret generic dingtalk-secret --from-literal=token=vei3ciex3lahphe1cos6ieThih3niwaizie6kaimi3wohCh5ipudih7Iec2aecai --from-literal=key=vei3ciex3lahphe1cos6ieThih3niwaizie6kaimi3wohCh5ipudih7Iec2aecai --dry-run -o yaml
apiVersion: v1
data:
  key: vei3ciex3lahphe1cos6ieThih3niwaizie6kaimi3wohCh5ipudih7Iec2aecai==
  token: vei3ciex3lahphe1cos6ieThih3niwaizie6kaimi3wohCh5ipudih7Iec2aecai==
kind: Secret
metadata:
  name: dingtalk-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dingtalk-hook
  name: dingtalk-hook
spec:
  selector:
    matchLabels:
      app: dingtalk-hook
  template:
    metadata:
      labels:
        app: dingtalk-hook
    spec:
      containers:
      - name: dingtalk-hook
        # image: yangpeng2468/alertmanager-dingtalk-hook:v1
        image: reg.chebai.org/paas/dingtalk-hook:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: ROBOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: dingtalk-secret
              key: token
        - name: LOG_LEVEL
          value: debug
        - name: ROBOT_SECRET
          valueFrom:
            secretKeyRef:
              name: dingtalk-secret
              key: key          
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dingtalk-hook
spec:
  selector:
    app: dingtalk-hook
  ports:
  - name: hook
    port: 5000
    targetPort: http