---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-headless
  labels:
    app: alertmanager
  namespace: monitor
spec:
  ports:
  - port: 9093
    name: database
  clusterIP: None
  selector:
    app: alertmanager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: alertmanager
  serviceName: "alertmanager"
  replicas: 2
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.18.0
        command: ["/bin/alertmanager"]
        args: ["--web.listen-address=0.0.0.0:9093", "--cluster.listen-address=0.0.0.0:9094", "--config.file=/etc/alertmanager/alertmanager.yml", "--storage.path=/alertmanager","--cluster.peer=alertmanager-0.alertmanager:9094"] 
        ports:
        - containerPort: 9093
          name: alertmanager
        - containerPort: 9094
          name: alert-cluster
        volumeMounts:
        - name: alertmanager-data
          mountPath: /alertmanager
        - mountPath: /etc/alertmanager/alertmanager.yml
          name: config
          subPath: alertmanager.yml
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: alertmanager.yml
            mode: 420
            path: alertmanager.yml
          name: alertmanager-config
        name: config
  volumeClaimTemplates:
  - metadata:
      name: alertmanager-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: "nfs"
      resources:
        requests:
          storage: 10Gi
