{
 "title": "k8s",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "environment",
    "query": "label_values(kube_node_info,environment)"
   },
   {
    "name": "Node",
    "query": "label_values(kube_node_info{environment='$env'},node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_labels{environment='$env'},namespace)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_container_info{environment='$env',namespace=~'^$namespace$'},pod)"
   },
   {
    "name": "PVC",
    "query": "label_values(kube_pod_spec_volumes_persistentvolumeclaims_info{environment='$env',namespace=~\"$namespace.*$\"},persistentvolumeclaim)"
   },
   {
    "name": "Deployment",
    "query": "label_values(kube_deployment_labels{environment='$env',namespace=~'^$namespace.*$'},deployment)"
   },
   {
    "name": "Daemonset",
    "query": "label_values(kube_daemonset_labels{environment='$env',namespace=~'^$namespace.*$'},daemonset)"
   },
   {
    "name": "Statefulset",
    "label": "Statefulset",
    "query": "label_values(kube_statefulset_labels{environment='$env',namespace=~'^$namespace.*$'},statefulset)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{environment=~\"^$env$\",image!=\"\",namespace=~\"^$namespace$\",pod_name=~\"^$Pod.*$\"}) or vector(0)) / sum(kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\",pod_name=~\"^$Pod.*$\"}[5m])) / (sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}))) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - ((sum(kube_deployment_status_replicas_available{environment=~\"^$env$\",namespace=~\"^$namespace$\",deployment=~\"$Deployment\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{environment=~\"^$env$\",namespace=~\"^$namespace$\",statefulset=~\"$Statefulset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{environment=~\"^$env$\",namespace=~\"^$namespace$\",daemonset=~\"$Daemonset\"}) or vector(0))) / ((sum(kube_deployment_status_replicas{environment=~\"^$env$\",namespace=~\"^$namespace$\",deployment=~\"$Deployment\"}) or vector(0)) + (sum(kube_statefulset_replicas{environment=~\"^$env$\",namespace=~\"^$namespace$\",statefulset=~\"$Statefulset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{environment=~\"^$env$\",namespace=~\"^$namespace$\",daemonset=~\"$Daemonset\"}) or vector(0))) ) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{environment=~\"^$env$\",image!=\"\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes{environment=~\"^$env$\",node=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\",pod_name=~\"^$Pod.*$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{environment=~\"^$env$\",namespace=~\"^$namespace$\",deployment=~\"$Deployment\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{environment=~\"^$env$\",namespace=~\"^$namespace$\",statefulset=~\"$Statefulset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{environment=~\"^$env$\",namespace=~\"^$namespace$\",daemonset=~\"$Daemonset\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(kube_deployment_status_replicas{environment=~\"^$env$\",namespace=~\"^$namespace$\",deployment=~\"$Deployment\"}) or vector(0)) + (sum(kube_statefulset_replicas{environment=~\"^$env$\",namespace=~\"^$namespace$\",statefulset=~\"$Statefulset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{environment=~\"^$env$\",namespace=~\"^$namespace$\",daemonset=~\"$Daemonset\"}) or vector(0)))"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "repeat": "namespace",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name, namespace) (rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) / (sum by(pod_name, namespace) (container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\"} / 100000)) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage(%)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "repeat": "namespace",
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 130 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 137 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    },
    {
     "title": "$namespace Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}[5m])) by(kubernetes_io_hostname,pod_name))/(sum(container_spec_cpu_quota{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\"}) by(kubernetes_io_hostname,pod_name) /100000)*100",
       "legendFormat": "pod: {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "repeat": "namespace",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 147 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 156 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 165 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 183 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name, namespace, job) (container_memory_rss{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) / sum by(pod_name, namespace, job) (container_spec_memory_limit_bytes{environment=~\"^$env$\",namespace=~\"^$namespace$\",image!=\"\"}) * 100 != +Inf",
       "legendFormat": "{{namespace }} | {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace PVC Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "repeat": "namespace",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (kubelet_volume_stats_used_bytes{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$namespace$\", persistentvolumeclaim=~\".*$PVC.*$\"} / kubelet_volume_stats_capacity_bytes{environment=~\"^$env$\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$namespace$\", persistentvolumeclaim=~\".*$PVC.*$\"})",
       "legendFormat": "{{ persistentvolumeclaim }} | {{ kubernetes_io_hostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network (receive)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace processes network I/O (receive)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "repeat": "namespace",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (receive)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (receive)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (receive)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (receive)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (receive)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (receive)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name,kubernetes_io_hostname)",
       "legendFormat": "-> {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network (transmit)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$namespace processes network I/O (transmit)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
     "repeat": "namespace",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum( rate (container_network_transmit_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (transmit)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum( rate (container_network_transmit_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (transmit)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum( rate (container_network_transmit_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (transmit)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum( rate (container_network_transmit_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (transmit)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum( rate (container_network_transmit_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (transmit)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum( rate (container_network_transmit_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    },
    {
     "title": "$namespace processes network I/O (transmit)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum( rate (container_network_transmit_bytes_total{environment=~\"^$env$\",id!=\"/\",namespace=~\"^$namespace$\", pod_name=~\"^$Pod.*$\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (pod_name, kubernetes_io_hostname)",
       "legendFormat": "<- {{ kubernetes_io_hostname }} | {{ pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}