{
 "title": "Node Exporter",
 "description": "使用 Node Exporter v0.16 0.17，精简优化重要指标展示。包含：CPU 内存 磁盘 IO 网络 温度等监控指标。https://github.com/starsliao/Prometheus",
 "tags": [
  "StarsL",
  "Prometheus",
  "node"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "env",
    "label": "environment",
    "query": "label_values(node_exporter_build_info,environment)"
   },
   {
    "name": "node",
    "label": "节点",
    "query": "label_values(up{environment='$env',job=~\".*node-exporter.*$\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  { "title": "节点基础信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "node" },
  {
   "title": "节点状态",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "文件句柄数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU iowait（5m）",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "CPU idle（5m）",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "CPU system（5m）",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "CPU user（5m）",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "CPU softirq（5m）",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"softirq\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "CPU irq（5m）",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"irq\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "CPU使用率、磁盘每秒的I/O操作耗费时间（%）",
     "type": "graph",
     "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m]))",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m]))",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m]))",
       "legendFormat": "Iowait"
      },
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{device}}_每秒I/O操作%"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存信息",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "总内存"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "已用"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "可用"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP 连接情况",
     "type": "graph",
     "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "ESTABLISHED"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "TCP_tw"
      },
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[5m])",
       "legendFormat": "ActiveOpens"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[5m])",
       "legendFormat": "PassiveOpens"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
       "legendFormat": "TCP_inuse"
      }
     ]
    },
    {
     "title": "当前打开的文件描述符",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$node\"}",
       "legendFormat": "open files"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "各分区可用空间",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~'$node',fstype=~\"ext4|xfs\",mountpoint!~\"/var/lib/kubelet|/var/lib/rancher\"}"
      },
      {
       "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\",mountpoint!~\"/var/lib/kubelet|/var/lib/rancher\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\",mountpoint!~\"/var/lib/kubelet|/var/lib/rancher\"})"
      }
     ]
    },
    {
     "title": "磁盘读写容量大小",
     "type": "graph",
     "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "Bps", "label": "读取（-）/写入（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{device}}_写入"
      }
     ]
    },
    {
     "title": "磁盘读写速率（IOPS）",
     "type": "graph",
     "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "读取（-）/写入（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{device}}-写入"
      },
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{device}}-读取"
      },
      {
       "expr": "node_disk_io_now{instance=~\"$node\"}",
       "legendFormat": "{{device}}-io"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  }
 ]
}