apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: database
  clusterIP: None
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb # has to match .spec.template.metadata.labels
  serviceName: "mariadb"  #声明它属于哪个Headless Service.
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mariadb # has to match .spec.selector.matchLabels
    spec:
      #terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb:10.3.17
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "111111"
        - name: MYSQL_USER
          value: "exporter"
        - name: MYSQL_PASSWORD
          value: "111111"
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:   #可看作pvc的模板
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-nfs-storage"  #存储类名，改为集群中已存在的
      resources:
        requests:
          storage: 10Gi
