apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: thanos-store
  name: thanos-store
  namespace: monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-store
  serviceName: thanos-store
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-store
    spec:
      containers:
      - args:
        - store
        - --data-dir=/var/thanos/store
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        #- --objstore.config=$(OBJSTORE_CONFIG)
        - --objstore.config-file=/etc/bucket/config.yaml
        #env:
        #- name: OBJSTORE_CONFIG
        #  valueFrom:
        #    secretKeyRef:
        #      key: thanos.yaml
        #      name: thanos-objectstorage
        image: thanosio/thanos:v0.9.0
        name: thanos-store
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
          - mountPath: /var/thanos/store
            name: thanos-store-data
            readOnly: false
          - name: bucketconfig
            mountPath: /etc/bucket
      volumes:
        - name: bucketconfig
          configMap:
            name: bucketconfig
  volumeClaimTemplates:
  - metadata:
      name: thanos-store-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      #storageClassName: standard
