apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: influxdb
  namespace: monitor
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    run: influxdb
status:
  loadBalancer: {}
